apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
         app: node-monitor
    spec:
      containers:
        - name: nonitor
          image: busybox
          command: ['sh', '-c', 'while true; do echo "Node $(NODE_NAME) alive"; sleep 10; done']
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
